# This is a basic workflow to help you get started with Actions

name: pytest

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  pytest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
#      - name: clone repository
#        run: |
#          git clone https://github.com/Lan-ce-lot/weibo-opinion-analysis
#          cd weibo-opinion-analysis
      - name: install pytest
        run: pip install pytest
      - name: run pytest
        run: pytest
